name: Update Submodules

on:
  push:
    branches:
      - main # Run only on pushes to the 'main' branch
  pull_request:
    branches:
      - main # Run on pull requests targeting the 'main' branch
  schedule:
    - cron: '0 0 * * 0' # Run every Sunday at midnight UTC
  workflow_dispatch: # Allow manual trigger of the workflow

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository with submodules
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive # Ensure submodules are checked out
          persist-credentials: true # Persist credentials for pushing changes

      # Step 2: Configure Git (required for pushing updates)
      - name: Set up Git User
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # Step 3: Update all submodules and push changes
      - name: Update and Push Submodules
        run: |
          git submodule update --remote --merge
          git add .
          git commit -m "Automated update of submodules" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Use GitHub-provided token for authentication
